---
- name: Install Wordpress and PHP
  block:
    - name: Copy nginx configuration from template for wordpress
      ansible.builtin.template:
        src: nginx-wordpress.conf.j2
        dest: /etc/nginx/conf.d/notls.conf
        owner: nginx
        group: nginx
        mode: 0644
      notify: restart nginx

    - name: Put repo files to /etc/yum.repos.d/ directory
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /etc/yum.repos.d/
        owner: root
        group: root
        mode: 0644
      with_items:
        - epel.repo
        - remi-php74.repo
        - remi-safe.repo

    - name: Install packages from 'php_packages_list'
      ansible.builtin.yum:
        name: "{{ item }}"
        update_cache: true
        state: present
      with_items: "{{ php_packages_list }}"

    - name: Remove default /etc/php-fpm.d/www.conf file
      ansible.builtin.file:
        path: /etc/php-fpm.d/www.conf
        state: absent

    - name: Disable SELinux
      selinux:
        state: disabled

    - name: Reboot machine to apply settings
      ansible.builtin.reboot:
        reboot_timeout: 600

    - name: Copy wordpress.conf from files to /etc/php-fpm.d/wordpress.conf
      ansible.builtin.copy:
        src: wordpress.conf
        dest: /etc/php-fpm.d/wordpress.conf
        owner: nginx
        group: nginx
        mode: 0644

    - name: >
        Download WordPress from http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
        to /srv/ folder + checksum
      ansible.builtin.get_url:
        url: http://wordpress.org/wordpress-{{ wp_version }}.tar.gz
        dest: /srv/
        checksum: "{{ wp_checksum }}"
        mode: 0644

    - name: Unarchive wordpress to /srv folder
      ansible.builtin.unarchive:
        src: /srv/wordpress-{{ wp_version }}.tar.gz
        dest: /srv
        owner: nginx
        group: nginx
        remote_src: true

    - name: Add linux group "wordpress"
      ansible.builtin.group:
        name: wordpress
        state: present

    - name: >
        Add linux user "wordpress" with group "wordpress"
        and /srv/wordpress as homedir
      ansible.builtin.user:
        name: wordpress
        group: wordpress
        home: /srv/wordpress

    - name: Create mariadb database for wordpress
      mysql_db:
        name: "{{ wp_db_name }}"
        state: present

    - name: Create WordPress database user
      no_log: true
      mysql_user:
        state: present
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: '{{ wp_db_name }}.*:ALL'

    - name: >
        Copy WordPress config file from templates
        to /srv/wordpress/wp-config.php
      ansible.builtin.template:
        src: wp-config.php.j2
        dest: /srv/wordpress/wp-config.php
        owner: wordpress
        group: wordpress
        mode: 0440

    - name: >
        /srv/wordpress directory recursive rights
        for wordpress user and group
      ansible.builtin.file:
        path: /srv/wordpress
        state: directory
        recurse: true
        owner: wordpress
        group: wordpress
        mode: 0755

    - name: Start php-fpm Service
      ansible.builtin.service:
        name: "php-fpm"
        state: started
      notify: restart php-fpm
